Updated to modern plugin for maven central publishing.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -13,16 +13,31 @@ jobs:
     permissions:
       contents: read
       packages: write
+    
+    env:
+      MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
+      MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Check Secrets
+        run: |
+          if [[ -z "${MAVEN_USERNAME}" ]]; then
+            echo "Error: CENTRAL_USERNAME secret is missing or empty."
+            exit 1
+          fi
+          if [[ -z "${MAVEN_PASSWORD}" ]]; then
+            echo "Error: CENTRAL_PASSWORD secret is missing or empty."
+            exit 1
+          fi
 
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
-          server-id: ossrh
+          server-id: central
           server-username: MAVEN_USERNAME
           server-password: MAVEN_PASSWORD
           gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
@@ -41,6 +56,3 @@ jobs:
 
       - name: Publish to Maven Central
         run: mvn --batch-mode deploy -P release -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
-        env:
-          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
-          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
